name: date_formatter_pro_example
description: "An example demonstrating the usage of the date_formatter_pro package."
publish_to: 'none' # This prevents publishing the example app to pub.dev

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  date_formatter_pro:
    path: ../ # This points to your package's root directory

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
