name: date_formatter_pro
description: "A Flutter package that provides flexible date formatting in various styles. Ideal for developers needing custom or localized date formats in their Flutter apps."
version: 0.0.4
repository: https://github.com/qasid1999/date-formatter-pro

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# Assets, fonts, etc. can be added here if needed

example: example/ # This points to the example directory containing a full Flutter project
